name: Automerge Release PR
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge-release:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release-please--')
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Auto-approve Release PR
        uses: hmarr/auto-approve-action@v4 # v4.0.0
        
      - name: Enable Auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
